"""Add foreign key constraints

Revision ID: c7a398305ff8
Revises: 6449b422ae52
Create Date: 2024-08-16 14:14:25.689877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7a398305ff8'
down_revision = '6449b422ae52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
